version: "3.9"

services:
  db:
    image: postgres
    restart: always
    container_name: db_postgres
    env_file:
      - ./.env
    volumes:
      - db_volume:/postgresql/data
    ports:
      - 5434:5432

  redis:
    image: redis
    restart: always
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - redis_volume:/redis/data
    ports:
      - ${REDIS_PORT}:6379

volumes:
  db_volume:
  redis_volume:
