version: "3.9"

services:
  db:
    image: postgres
    restart: always
    container_name: db_postgres
    env_file:
      - ./.env
    volumes:
      - db_volume:/postgresql/data
    ports:
      - 5434:5432

volumes:
  db_volume:
