# Generated by Django 4.0.3 on 2022-04-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False, unique=True, verbose_name='Spotify id')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrArtistsAndGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.artists')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.group')),
            ],
        ),
    ]
