# Generated by Django 4.0.3 on 2022-04-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='artists',
            name='id',
            field=models.CharField(max_length=22, primary_key=True, serialize=False, unique=True, verbose_name='spotify id'),
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False, unique=True, verbose_name='spotify id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(max_length=255, verbose_name='single/album')),
                ('images', models.CharField(max_length=255, verbose_name='in future ForeignKey(Images)')),
                ('release_date', models.CharField(max_length=255, verbose_name='in future Date')),
                ('total_track', models.IntegerField(verbose_name='if album - count track, if single - 1')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.crartistsandgroup')),
            ],
        ),
    ]
