# Generated by Django 4.0.3 on 2022-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_images_alter_artists_id_releases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crartistsandgroup',
            old_name='id_artists',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='crartistsandgroup',
            old_name='id_group',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='releases',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
