# Generated by Django 3.2.11 on 2022-04-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_rename_id_artists_crartistsandgroup_artists_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrArtistsAndReleases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.artists')),
            ],
        ),
        migrations.RemoveField(
            model_name='releases',
            name='performer',
        ),
        migrations.AlterField(
            model_name='releases',
            name='images',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='in future ForeignKey(Images)'),
        ),
        migrations.AlterField(
            model_name='releases',
            name='total_track',
            field=models.IntegerField(null=True, verbose_name='if album - count track, if single - 1'),
        ),
        migrations.DeleteModel(
            name='CrArtistsAndGroup',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='crartistsandreleases',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.releases'),
        ),
    ]
