# Generated by Django 4.0.3 on 2022-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_alter_artists_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='releases',
            name='artists',
            field=models.ManyToManyField(to='song.artists'),
        ),
        migrations.DeleteModel(
            name='CrArtistsAndReleases',
        ),
    ]
