# Generated by Django 4.0.3 on 2022-04-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_datafromspotify'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='ArtistsInstance',
        ),
        migrations.RenameModel(
            old_name='DataFromSpotify',
            new_name='DataFromSpotifyInstance',
        ),
        migrations.RenameModel(
            old_name='Releases',
            new_name='ReleasesInstance',
        ),
    ]
