# Generated by Django 4.0.3 on 2022-06-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0010_imagesinstance_delete_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFromSpotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_loading', models.DateTimeField(auto_now_add=True, verbose_name='time_loading')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='DataFromSpotifyInstance',
        ),
    ]
