# Generated by Django 4.0.3 on 2022-06-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0011_datafromspotify_delete_datafromspotifyinstance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistsInstance',
            new_name='Artists',
        ),
        migrations.RenameModel(
            old_name='ImagesInstance',
            new_name='Images',
        ),
        migrations.RenameModel(
            old_name='ReleasesInstance',
            new_name='Releases',
        ),
        migrations.AlterModelTable(
            name='artists',
            table='artists',
        ),
        migrations.AlterModelTable(
            name='datafromspotify',
            table='data_from_spotify',
        ),
        migrations.AlterModelTable(
            name='images',
            table='images',
        ),
        migrations.AlterModelTable(
            name='releases',
            table='releases',
        ),
    ]
