# Generated by Django 4.0.3 on 2022-06-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0012_rename_artistsinstance_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releases',
            name='images',
        ),
        migrations.AddField(
            model_name='releases',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.images'),
        ),
    ]
