# Generated by Django 4.0.3 on 2022-06-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0013_remove_releases_images_releases_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.images'),
        ),
    ]
