# Generated by Django 4.0.3 on 2022-06-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0014_alter_releases_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releases',
            name='artists',
        ),
        migrations.AddField(
            model_name='releases',
            name='artists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.artists'),
        ),
    ]
