# Generated by Django 4.0.3 on 2022-06-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0015_remove_releases_artists_releases_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='artists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.artists'),
        ),
    ]
