# Generated by Django 4.0.3 on 2022-06-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0016_alter_releases_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releases',
            name='artists',
        ),
        migrations.AddField(
            model_name='releases',
            name='artists',
            field=models.ManyToManyField(to='song.artists'),
        ),
    ]
