# Generated by Django 4.0.3 on 2022-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.IntegerField(blank=True, verbose_name='telegram chat id'),
        ),
    ]
