# Generated by Django 4.0.3 on 2022-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, verbose_name='telegram chat id'),
        ),
    ]
