# Generated by Django 4.0.3 on 2022-03-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_tg_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.IntegerField(default=None, null=True, verbose_name='telegram chat id'),
        ),
    ]
